@extends('layouts.main')
@section('content')


<div class="container flex">
    <div id="default-carousel" class="relative w-full px-16 pt-8" data-carousel="slide">
        <!-- Carousel wrapper -->
        <div class="relative h-56 overflow-hidden rounded-lg md:h-96">
            <!-- Item 1 -->
            <div class="transition-opacity duration-700 ease-in-out opacity-0" data-carousel-item>
                <img src="{{ asset('images/img1.jpg') }}" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
            </div>
            <!-- Item 2 -->
            <div class="transition-opacity duration-700 ease-in-out opacity-0" data-carousel-item>
                <img src="{{ asset('images/img2.jpg') }}" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
            </div>
            <!-- Item 3 -->
            <div class="transition-opacity duration-700 ease-in-out opacity-0" data-carousel-item>
                <img src="{{ asset('images/img3.jpg') }}" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
            </div>
        </div>
        <!-- Slider indicators -->
        <div class="absolute z-30 flex justify-center bottom-5 left-1/2 transform -translate-x-1/2 space-x-3 rtl:space-x-reverse">
            <!-- Indicators will be generated by JavaScript -->
        </div>
        <!-- Slider controls -->
        <button type="button" class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
            <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
                </svg>
                <span class="sr-only">Previous</span>
            </span>
        </button>
        <button type="button" class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
            <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                </svg>
                <span class="sr-only">Next</span>
            </span>
        </button>
    </div>
    <div class="text-4xl font-semibold mt-8">
        Jalur Penerimaan Universitas MDP
    </div>
    <div>
        Universitas MDP memberikan beasiswa kepada calon mahasiswa yang berprestasi
    </div>
    <div class="card mt-8 mb-8 flex gap-8">
        <!-- Item 1 -->
        <div class="max-w-sm p-6 bg-gray-900 border border-gray-700 rounded-lg shadow">
            <a href="#">
                <h5 class="mb-2 text-2xl font-semibold tracking-tight text-white">Pascasarjana Magister Sistem Informasi (S2)</h5>
            </a>
            <p class="mb-3 font-normal text-gray-400">Program Magister Sistem Informasi Universitas MDP memberikan kesempatan studi lanjut bagi lulusan S1 Semua Program Studi.</p>
            <a href="#" class="inline-flex font-medium items-center text-blue-600 hover:underline">
                Daftar sekarang!
                <svg class="w-3 h-3 ms-2.5 rtl:rotate-[270deg]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11v4.833A1.166 1.166 0 0 1 13.833 17H2.167A1.167 1.167 0 0 1 1 15.833V4.167A1.166 1.166 0 0 1 2.167 3h4.618m4.447-2H17v5.768M9.111 8.889l7.778-7.778"/>
                </svg>
            </a>
        </div>
        <!-- Item 2 -->
        <div class="max-w-sm p-6 bg-gray-900 border border-gray-700 rounded-lg shadow">
            <a href="#">
                <h5 class="mb-2 text-2xl font-semibold tracking-tight text-white">Jalur Tes</h5>
            </a>
            <p class="mb-3 font-normal text-gray-400">Universitas MDP memiliki beberapa jalur seleksi, antara lain adalah Ujian Tulis Mandiri Berbasis Komputer, Ujian Tulis Berbasis Manajemen, Ujian Tulis Berbasis Akuntansi.</p>
            <a href="#" class="inline-flex font-medium items-center text-blue-600 hover:underline">
                Daftar sekarang!
                <svg class="w-3 h-3 ms-2.5 rtl:rotate-[270deg]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11v4.833A1.166 1.166 0 0 1 13.833 17H2.167A1.167 1.167 0 0 1 1 15.833V4.167A1.166 1.166 0 0 1 2.167 3h4.618m4.447-2H17v5.768M9.111 8.889l7.778-7.778"/>
                </svg>
            </a>
        </div>
        <!-- Item 3 -->
        <div class="max-w-sm p-6 bg-gray-900 border border-gray-700 rounded-lg shadow">
            <a href="#">
                <h5 class="mb-2 text-2xl font-semibold tracking-tight text-white">Program Beasiswa Jalur UTBK</h5>
            </a>
            <p class="mb-3 font-normal text-gray-400">Kuliah di Universitas MDP Menggunakan Nilai UTBK SNBT 2024, perolehan jumlah beasiswa yang dapat di raih oleh mahasiswa sesuai dengan nilai UTBK.</p>
            <a href="#" class="inline-flex font-medium items-center text-blue-600 hover:underline">
                Daftar sekarang!
                <svg class="w-3 h-3 ms-2.5 rtl:rotate-[270deg]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11v4.833A1.166 1.166 0 0 1 13.833 17H2.167A1.167 1.167 0 0 1 1 15.833V4.167A1.166 1.166 0 0 1 2.167 3h4.618m4.447-2H17v5.768M9.111 8.889l7.778-7.778"/>
                </svg>
            </a>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const carousel = document.querySelector('#default-carousel');
        const items = document.querySelectorAll('[data-carousel-item]');
        const totalItems = items.length;
        let currentIndex = 0;

        // Create indicators
        const indicatorsContainer = document.querySelector('[data-carousel="slide"] .absolute.z-30.flex');
        items.forEach((_, i) => {
            const dot = document.createElement('button');
            dot.className = 'w-3 h-3 rounded-full bg-gray-400';
            dot.setAttribute('aria-label', `Slide ${i + 1}`);
            dot.dataset.carouselSlideTo = i;
            indicatorsContainer.appendChild(dot);
        });

        const indicators = document.querySelectorAll('[data-carousel="slide"] .absolute.z-30.flex button');

        function updateIndicators(index) {
            indicators.forEach((indicator, i) => {
                indicator.classList.toggle('bg-gray-700', i === index);
                indicator.classList.toggle('bg-gray-400', i !== index);
            });
        }

        function showSlide(index) {
            items.forEach((item, i) => {
                if (i === index) {
                    item.classList.remove('opacity-0');
                    item.classList.add('opacity-100');
                } else {
                    item.classList.remove('opacity-100');
                    item.classList.add('opacity-0');
                }
            });
            updateIndicators(index);
        }

        function nextSlide() {
            currentIndex = (currentIndex + 1) % totalItems;
            showSlide(currentIndex);
        }

        function prevSlide() {
            currentIndex = (currentIndex - 1 + totalItems) % totalItems;
            showSlide(currentIndex);
        }

        document.querySelector('[data-carousel-next]').addEventListener('click', nextSlide);
        document.querySelector('[data-carousel-prev]').addEventListener('click', prevSlide);

        indicators.forEach(indicator => {
            indicator.addEventListener('click', function() {
                const slideIndex = parseInt(this.dataset.carouselSlideTo, 10);
                currentIndex = slideIndex;
                showSlide(slideIndex);
            });
        });

        // Initialize carousel
        showSlide(currentIndex);

        // Automatic sliding
        setInterval(nextSlide, 5000); // Change slide every 5 seconds
    });
</script>
@endsection
